using System.Text;



namespace DirectInserttoDB
{

  


    internal class Program
    {
        const string ConnectionString = "Host=localhost;Port=5432;Database=WaterTank;Username=postgres;Password=mypassword"; // i know
        enum DbMode
        {
            MultipleAutoGeneratedInsertions,
            Custom
        }


        static async Task<int> Main()
        {
            DbMode? mode = null;
            StringBuilder sb = new();
            int counter = 1;

            var modes = Enum.GetValues<DbMode>();
            if (modes is null || modes.Length == 0) return 0;

            foreach (var item in modes)
            {
                sb.Append($".{counter++} {item} ");
            }

            sb.Length--;

            while (true)
            {

                Console.Write($"Choose mode ({sb}): ");

                string? inputMode = Console.ReadLine();
                if (int.TryParse(inputMode, out int result))
                {
                    --result;
                    if(result <= modes.Length)
                    {
                        mode = (DbMode)result;
                        break;
                    }
                    else
                    {
                        Console.WriteLine("invalid mode");
                    }
                }
                else Console.WriteLine("invalid mode");


            }
            Console.Clear();


            switch (mode)
            {
                case DbMode.MultipleAutoGeneratedInsertions: await new DBBulkinsert(ConnectionString).Start(); break;
                case DbMode.Custom: await new DbCustomInsert(ConnectionString).Start(); break;
                default: throw new NotImplementedException("mode not found");
            }




            Console.WriteLine("done");


            return 0;



        }


       




    }
}
